# Generated by Django 3.1.3 on 2021-01-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('image', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
    ]
