# Generated by Django 3.1.3 on 2021-01-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appalone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
